import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ThemeProvider from "@/provider/ThemeProvider";
import Footer from "@/components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400", "500", "700"],
  preload: true,
});

// const cairo = Cairo({
//   subsets: ["latin"],
//   weight: ["400", "500", "700"],
//   preload: true,
// });

export const metadata: Metadata = {
  title: "Yassin Ibrahim | Portfoio",
  description: "Generated by create next app",
  icons: {
    icon: "/me.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} transition-colors duration-100 ease-linear overflow-x-hidden`}
      >
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
